sudo: required
services:
  - docker

before_install:
  - docker build -t macborowy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true macborowy/docker-react npm run test -- --coverage